apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: svqol9t5g-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:bfe60187a023e9d15ed26f91b2925d5c78ca6cf5@sha256:88f8a5e6bf1ae13aa60f806173bb1c814b683b0e707284f15dab894b7a38694f
          name: container-image
