apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: svqol9t5g-go
  janus-idp.io/tekton: svqol9t5g-go
  backstage.io/kubernetes-id: svqol9t5g-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: svqol9t5g-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
